.PHONY: core nlohmann_json noob ssh-askpass uti

all: core nlohmann_json noob ssh-askpass uti

core:
	git submodule add -f https://github.com/JarryShaw/homebrew-core.git jarryshaw-core

nlohmann_json:
	git submodule add -f https://github.com/nlohmann/homebrew-json.git nlohmann-json

noob:
	git submodule add -f https://github.com/zmwangx/homebrew-npm-noob.git zmwangx-npm-noob

ssh-askpass:
	git submodule add -f https://github.com/theseal/homebrew-ssh-askpass.git theseal-ssh-askpass

uti:
	git submodule add -f https://github.com/alexaubry/homebrew-formulas.git alexaubry-formulas
