name: "Cron Job for Formula"

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: master

jobs:
  update:
    runs-on: macos-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Setup requirements & Update submodules
        run: |
          set -x

          python -m pip install -r Generator/requirements.txt

          git submodule update --init --recursive
          git submodule foreach git checkout master
          git submodule foreach git pull

      - name: make formula (Python)
        working-directory: Generator
        run: |
          for name in bandit dmgbuild docutils f2format jshint macdaily poseur pydl snooty-lextudio sphinx vermin walrus zkg; do
            echo "+ pip install ${name}"
            python -m pip install ${name}

            echo "+ make ${name}"
            python scripts/${name}.py

            echo "+ pip uninstall ${name}"
            pip-autoremove -y ${name}
          done

      - name: make formula (Others)
        working-directory: Generator
        run: |
          for name in appdmg basher dmgbuild git-hg jshint mirror-config-china node-sass noob sloc; do
            echo "+ make ${name}"
            python scripts/${name}.py
          done

      - name: make fetch
        working-directory: Generator
        run: |
          for name in amass dart dart-beta dart-sass pyinstaller nlohmann-json ssh-askpass uti; do
            echo "+ make ${name}"
            python scripts/${name}.py
          done

      - name: make link
        working-directory: Generator
        run: |
          make link

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Regular update at $(date)" -a

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
